package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseGoodsAttributeRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsAttributeRef extends BaseGoodsAttributeRef<GoodsAttributeRef> {
	
	public static final GoodsAttributeRef dao = new GoodsAttributeRef().dao();
	
}

