package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseGoodsImageRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GoodsImageRef extends BaseGoodsImageRef<GoodsImageRef> {
	public static final GoodsImageRef dao = new GoodsImageRef().dao();
}

