package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseMsgNoticeSend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MsgNoticeSend extends BaseMsgNoticeSend<MsgNoticeSend> {
	
	public static final MsgNoticeSend dao = new MsgNoticeSend().dao();
	
	
	public MsgNotice getMsgNotice() {
		return MsgNotice.dao.findById(getMsgNoticeId());
	}
	
	public MsgNoticeSend findBy(Integer id) {
		return MsgNoticeSend.dao.findFirst("select * from msg_notice_send where id = ?", id);
	}
	
}

