package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BasePurchaseOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseOrderLog extends BasePurchaseOrderLog<PurchaseOrderLog> {
	public static final PurchaseOrderLog dao = new PurchaseOrderLog().dao();
}

