package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BasePurchaseRejectOrderCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseRejectOrderCost extends BasePurchaseRejectOrderCost<PurchaseRejectOrderCost> {
	public static final PurchaseRejectOrderCost dao = new PurchaseRejectOrderCost().dao();
}

