package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BasePurchaseRejectOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseRejectOrderLog extends BasePurchaseRejectOrderLog<PurchaseRejectOrderLog> {
	public static final PurchaseRejectOrderLog dao = new PurchaseRejectOrderLog().dao();
}

