package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.CommonConstant;
import com.bytechainx.psi.common.model.base.BaseSaleRejectOrderFee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleRejectOrderFee extends BaseSaleRejectOrderFee<SaleRejectOrderFee> {
	
	public static final SaleRejectOrderFee dao = new SaleRejectOrderFee().dao();
	
	/**
	 * 项目开支类型
	 * @return
	 */
	public TraderFundType getFundType() {
		return TraderFundType.dao.findFirstByCache(CommonConstant.CACHE_NAME_ONE_MINUTE_STORE, "trader.fund.type.id."+getTraderFundType(), "select * from trader_fund_type where id = ?", getTraderFundType());
	}
	
	public SaleRejectOrderFee findByFundType(Integer orderId, Integer fundType) {
		return SaleRejectOrderFee.dao.findFirst("select * from sale_reject_order_fee where sale_reject_order_id = ? and trader_fund_type = ?", orderId, fundType);
	}
	
}

