package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseSaleOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleOrderLog extends BaseSaleOrderLog<SaleOrderLog> {
	public static final SaleOrderLog dao = new SaleOrderLog().dao();
}

