package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseSaleRejectOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleRejectOrderLog extends BaseSaleRejectOrderLog<SaleRejectOrderLog> {
	public static final SaleRejectOrderLog dao = new SaleRejectOrderLog().dao();
}

