package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseSaleRejectOrderCost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SaleRejectOrderCost extends BaseSaleRejectOrderCost<SaleRejectOrderCost> {
	public static final SaleRejectOrderCost dao = new SaleRejectOrderCost().dao();
}

