package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTenantSmsLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TenantSmsLog extends BaseTenantSmsLog<TenantSmsLog> {
	public static final TenantSmsLog dao = new TenantSmsLog().dao();
}

