package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTenantRoleOperRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TenantRoleOperRef extends BaseTenantRoleOperRef<TenantRoleOperRef> {
	public static final TenantRoleOperRef dao = new TenantRoleOperRef().dao();
}

