package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTraderBookAccountLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraderBookAccountLogs extends BaseTraderBookAccountLogs<TraderBookAccountLogs> {
	public static final TraderBookAccountLogs dao = new TraderBookAccountLogs().dao();
}

