package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTraderPayOrderFund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraderPayOrderFund extends BaseTraderPayOrderFund<TraderPayOrderFund> {
	
	public static final TraderPayOrderFund dao = new TraderPayOrderFund().dao();
	
	public TraderBalanceAccount getBalanceAccount() {
		return TraderBalanceAccount.dao.findById(getTraderBalanceAccountId());
	}
}

