package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTraderReceiptOrderRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraderReceiptOrderRef extends BaseTraderReceiptOrderRef<TraderReceiptOrderRef> {
	
	public static final TraderReceiptOrderRef dao = new TraderReceiptOrderRef().dao();
	
	public SaleOrder getSaleOrder() {
		return SaleOrder.dao.findById(getSaleOrderId());
	}

	public TraderReceiptOrder getTraderReceiptOrder() {
		return TraderReceiptOrder.dao.findById(getTraderReceiptOrderId());
	}
}

