package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTraderReceiptOrderFund;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraderReceiptOrderFund extends BaseTraderReceiptOrderFund<TraderReceiptOrderFund> {
	
	public static final TraderReceiptOrderFund dao = new TraderReceiptOrderFund().dao();
	
	public TraderBalanceAccount getBalanceAccount() {
		return TraderBalanceAccount.dao.findById(getTraderBalanceAccountId());
	}
}

