package com.bytechainx.psi.common.model;

import com.bytechainx.psi.common.model.base.BaseTraderPayOrderRef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TraderPayOrderRef extends BaseTraderPayOrderRef<TraderPayOrderRef> {
	public static final TraderPayOrderRef dao = new TraderPayOrderRef().dao();

	public TraderReceiptOrder getTraderPayOrder() {
		return TraderReceiptOrder.dao.findById(getTraderPayOrderId());
	}

	public PurchaseOrder getPurchaseOrder() {
		return PurchaseOrder.dao.findById(getPurchaseOrderId());
	}
}

