package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraderSupplierPayable<M extends BaseTraderSupplierPayable<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setSupplierInfoId(java.lang.Integer supplierInfoId) {
		set("supplier_info_id", supplierInfoId);
	}
	
	public java.lang.Integer getSupplierInfoId() {
		return getInt("supplier_info_id");
	}
	
	public void setTraderBookAccountId(java.lang.Integer traderBookAccountId) {
		set("trader_book_account_id", traderBookAccountId);
	}
	
	public java.lang.Integer getTraderBookAccountId() {
		return getInt("trader_book_account_id");
	}
	
	public void setRefOrderType(java.lang.Integer refOrderType) {
		set("ref_order_type", refOrderType);
	}
	
	public java.lang.Integer getRefOrderType() {
		return getInt("ref_order_type");
	}
	
	public void setRefOrderId(java.lang.Integer refOrderId) {
		set("ref_order_id", refOrderId);
	}
	
	public java.lang.Integer getRefOrderId() {
		return getInt("ref_order_id");
	}
	
	public void setRefOrderCode(java.lang.String refOrderCode) {
		set("ref_order_code", refOrderCode);
	}
	
	public java.lang.String getRefOrderCode() {
		return getStr("ref_order_code");
	}
	
	public void setNewAmount(java.math.BigDecimal newAmount) {
		set("new_amount", newAmount);
	}
	
	public java.math.BigDecimal getNewAmount() {
		return getBigDecimal("new_amount");
	}
	
	public void setTakeAmount(java.math.BigDecimal takeAmount) {
		set("take_amount", takeAmount);
	}
	
	public java.math.BigDecimal getTakeAmount() {
		return getBigDecimal("take_amount");
	}
	
	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
	}
	
	public java.math.BigDecimal getDiscountAmount() {
		return getBigDecimal("discount_amount");
	}
	
	public void setAdjustAmount(java.math.BigDecimal adjustAmount) {
		set("adjust_amount", adjustAmount);
	}
	
	public java.math.BigDecimal getAdjustAmount() {
		return getBigDecimal("adjust_amount");
	}
	
	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}
	
	public java.util.Date getOrderTime() {
		return getDate("order_time");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

