package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsSpecRef<M extends BaseGoodsSpecRef<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGoodsInfoId(java.lang.Integer goodsInfoId) {
		set("goods_info_id", goodsInfoId);
	}
	
	public java.lang.Integer getGoodsInfoId() {
		return getInt("goods_info_id");
	}
	
	public void setGoodsSpecId(java.lang.Integer goodsSpecId) {
		set("goods_spec_id", goodsSpecId);
	}
	
	public java.lang.Integer getGoodsSpecId() {
		return getInt("goods_spec_id");
	}
	
	public void setSpecValue(java.lang.String specValue) {
		set("spec_value", specValue);
	}
	
	public java.lang.String getSpecValue() {
		return getStr("spec_value");
	}
	
	public void setPosition(java.lang.Integer position) {
		set("position", position);
	}
	
	public java.lang.Integer getPosition() {
		return getInt("position");
	}
	
}

