package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSaleOrderLog<M extends BaseSaleOrderLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setSaleOrderId(java.lang.Integer saleOrderId) {
		set("sale_order_id", saleOrderId);
	}
	
	public java.lang.Integer getSaleOrderId() {
		return getInt("sale_order_id");
	}
	
	public void setOperTime(java.util.Date operTime) {
		set("oper_time", operTime);
	}
	
	public java.util.Date getOperTime() {
		return getDate("oper_time");
	}
	
	public void setOperDesc(java.lang.String operDesc) {
		set("oper_desc", operDesc);
	}
	
	public java.lang.String getOperDesc() {
		return getStr("oper_desc");
	}
	
	public void setOperAdminName(java.lang.String operAdminName) {
		set("oper_admin_name", operAdminName);
	}
	
	public java.lang.String getOperAdminName() {
		return getStr("oper_admin_name");
	}
	
	public void setOperAdminId(java.lang.Integer operAdminId) {
		set("oper_admin_id", operAdminId);
	}
	
	public java.lang.Integer getOperAdminId() {
		return getInt("oper_admin_id");
	}
	
}

