package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemOper<M extends BaseSystemOper<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOperType(java.lang.Integer operType) {
		set("oper_type", operType);
	}
	
	public java.lang.Integer getOperType() {
		return getInt("oper_type");
	}
	
	public void setOperName(java.lang.String operName) {
		set("oper_name", operName);
	}
	
	public java.lang.String getOperName() {
		return getStr("oper_name");
	}
	
	public void setOperCode(java.lang.String operCode) {
		set("oper_code", operCode);
	}
	
	public java.lang.String getOperCode() {
		return getStr("oper_code");
	}
	
	public void setModuleCode(java.lang.String moduleCode) {
		set("module_code", moduleCode);
	}
	
	public java.lang.String getModuleCode() {
		return getStr("module_code");
	}
	
	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}
	
}

