package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraderBookAccountLogs<M extends BaseTraderBookAccountLogs<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setTraderBookAccountId(java.lang.Integer traderBookAccountId) {
		set("trader_book_account_id", traderBookAccountId);
	}
	
	public java.lang.Integer getTraderBookAccountId() {
		return getInt("trader_book_account_id");
	}
	
	public void setFundFlow(java.lang.Integer fundFlow) {
		set("fund_flow", fundFlow);
	}
	
	public java.lang.Integer getFundFlow() {
		return getInt("fund_flow");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setBalance(java.math.BigDecimal balance) {
		set("balance", balance);
	}
	
	public java.math.BigDecimal getBalance() {
		return getBigDecimal("balance");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

