package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchaseOrderGoods<M extends BasePurchaseOrderGoods<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setSupplierInfoId(java.lang.Integer supplierInfoId) {
		set("supplier_info_id", supplierInfoId);
	}
	
	public java.lang.Integer getSupplierInfoId() {
		return getInt("supplier_info_id");
	}
	
	public void setPurchaseOrderId(java.lang.Integer purchaseOrderId) {
		set("purchase_order_id", purchaseOrderId);
	}
	
	public java.lang.Integer getPurchaseOrderId() {
		return getInt("purchase_order_id");
	}
	
	public void setGoodsInfoId(java.lang.Integer goodsInfoId) {
		set("goods_info_id", goodsInfoId);
	}
	
	public java.lang.Integer getGoodsInfoId() {
		return getInt("goods_info_id");
	}
	
	public void setSpec1Id(java.lang.Integer spec1Id) {
		set("spec_1_id", spec1Id);
	}
	
	public java.lang.Integer getSpec1Id() {
		return getInt("spec_1_id");
	}
	
	public void setSpecOption1Id(java.lang.Integer specOption1Id) {
		set("spec_option_1_id", specOption1Id);
	}
	
	public java.lang.Integer getSpecOption1Id() {
		return getInt("spec_option_1_id");
	}
	
	public void setSpec2Id(java.lang.Integer spec2Id) {
		set("spec_2_id", spec2Id);
	}
	
	public java.lang.Integer getSpec2Id() {
		return getInt("spec_2_id");
	}
	
	public void setSpecOption2Id(java.lang.Integer specOption2Id) {
		set("spec_option_2_id", specOption2Id);
	}
	
	public java.lang.Integer getSpecOption2Id() {
		return getInt("spec_option_2_id");
	}
	
	public void setSpec3Id(java.lang.Integer spec3Id) {
		set("spec_3_id", spec3Id);
	}
	
	public java.lang.Integer getSpec3Id() {
		return getInt("spec_3_id");
	}
	
	public void setSpecOption3Id(java.lang.Integer specOption3Id) {
		set("spec_option_3_id", specOption3Id);
	}
	
	public java.lang.Integer getSpecOption3Id() {
		return getInt("spec_option_3_id");
	}
	
	public void setUnitId(java.lang.Integer unitId) {
		set("unit_id", unitId);
	}
	
	public java.lang.Integer getUnitId() {
		return getInt("unit_id");
	}
	
	public void setBuyNumber(java.math.BigDecimal buyNumber) {
		set("buy_number", buyNumber);
	}
	
	public java.math.BigDecimal getBuyNumber() {
		return getBigDecimal("buy_number");
	}
	
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return getBigDecimal("price");
	}
	
	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return getBigDecimal("discount");
	}
	
	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
	}
	
	public java.math.BigDecimal getDiscountAmount() {
		return getBigDecimal("discount_amount");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setRejectType(java.lang.Integer rejectType) {
		set("reject_type", rejectType);
	}
	
	public java.lang.Integer getRejectType() {
		return getInt("reject_type");
	}
	
	public void setRejectNumber(java.math.BigDecimal rejectNumber) {
		set("reject_number", rejectNumber);
	}
	
	public java.math.BigDecimal getRejectNumber() {
		return getBigDecimal("reject_number");
	}
	
	public void setRejectAmount(java.math.BigDecimal rejectAmount) {
		set("reject_amount", rejectAmount);
	}
	
	public java.math.BigDecimal getRejectAmount() {
		return getBigDecimal("reject_amount");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

