package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenantPrintTemplate<M extends BaseTenantPrintTemplate<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setPaperType(java.lang.String paperType) {
		set("paper_type", paperType);
	}
	
	public java.lang.String getPaperType() {
		return getStr("paper_type");
	}
	
	public void setPrintMode(java.lang.Integer printMode) {
		set("print_mode", printMode);
	}
	
	public java.lang.Integer getPrintMode() {
		return getInt("print_mode");
	}
	
	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public void setTplPic(java.lang.String tplPic) {
		set("tpl_pic", tplPic);
	}
	
	public java.lang.String getTplPic() {
		return getStr("tpl_pic");
	}
	
	public void setTplCss(java.lang.String tplCss) {
		set("tpl_css", tplCss);
	}
	
	public java.lang.String getTplCss() {
		return getStr("tpl_css");
	}
	
	public void setDefaultFlag(java.lang.Boolean defaultFlag) {
		set("default_flag", defaultFlag);
	}
	
	public java.lang.Boolean getDefaultFlag() {
		return getBoolean("default_flag");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

