package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraderReceiptOrderRef<M extends BaseTraderReceiptOrderRef<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setTraderReceiptOrderId(java.lang.Integer traderReceiptOrderId) {
		set("trader_receipt_order_id", traderReceiptOrderId);
	}
	
	public java.lang.Integer getTraderReceiptOrderId() {
		return getInt("trader_receipt_order_id");
	}
	
	public void setSaleOrderId(java.lang.Integer saleOrderId) {
		set("sale_order_id", saleOrderId);
	}
	
	public java.lang.Integer getSaleOrderId() {
		return getInt("sale_order_id");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
	}
	
	public java.math.BigDecimal getDiscountAmount() {
		return getBigDecimal("discount_amount");
	}
	
}

