package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInventoryCheckingGoods<M extends BaseInventoryCheckingGoods<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setInventoryCheckingId(java.lang.Integer inventoryCheckingId) {
		set("inventory_checking_id", inventoryCheckingId);
	}
	
	public java.lang.Integer getInventoryCheckingId() {
		return getInt("inventory_checking_id");
	}
	
	public void setGoodsInfoId(java.lang.Integer goodsInfoId) {
		set("goods_info_id", goodsInfoId);
	}
	
	public java.lang.Integer getGoodsInfoId() {
		return getInt("goods_info_id");
	}
	
	public void setSpec1Id(java.lang.Integer spec1Id) {
		set("spec_1_id", spec1Id);
	}
	
	public java.lang.Integer getSpec1Id() {
		return getInt("spec_1_id");
	}
	
	public void setSpecOption1Id(java.lang.Integer specOption1Id) {
		set("spec_option_1_id", specOption1Id);
	}
	
	public java.lang.Integer getSpecOption1Id() {
		return getInt("spec_option_1_id");
	}
	
	public void setSpec2Id(java.lang.Integer spec2Id) {
		set("spec_2_id", spec2Id);
	}
	
	public java.lang.Integer getSpec2Id() {
		return getInt("spec_2_id");
	}
	
	public void setSpecOption2Id(java.lang.Integer specOption2Id) {
		set("spec_option_2_id", specOption2Id);
	}
	
	public java.lang.Integer getSpecOption2Id() {
		return getInt("spec_option_2_id");
	}
	
	public void setSpec3Id(java.lang.Integer spec3Id) {
		set("spec_3_id", spec3Id);
	}
	
	public java.lang.Integer getSpec3Id() {
		return getInt("spec_3_id");
	}
	
	public void setSpecOption3Id(java.lang.Integer specOption3Id) {
		set("spec_option_3_id", specOption3Id);
	}
	
	public java.lang.Integer getSpecOption3Id() {
		return getInt("spec_option_3_id");
	}
	
	public void setUnitId(java.lang.Integer unitId) {
		set("unit_id", unitId);
	}
	
	public java.lang.Integer getUnitId() {
		return getInt("unit_id");
	}
	
	public void setCheckNumber(java.math.BigDecimal checkNumber) {
		set("check_number", checkNumber);
	}
	
	public java.math.BigDecimal getCheckNumber() {
		return getBigDecimal("check_number");
	}
	
	public void setConvertNumber(java.math.BigDecimal convertNumber) {
		set("convert_number", convertNumber);
	}
	
	public java.math.BigDecimal getConvertNumber() {
		return getBigDecimal("convert_number");
	}
	
	public void setCurrentNumber(java.math.BigDecimal currentNumber) {
		set("current_number", currentNumber);
	}
	
	public java.math.BigDecimal getCurrentNumber() {
		return getBigDecimal("current_number");
	}
	
	public void setProfitLoss(java.math.BigDecimal profitLoss) {
		set("profit_loss", profitLoss);
	}
	
	public java.math.BigDecimal getProfitLoss() {
		return getBigDecimal("profit_loss");
	}
	
	public void setGoodsBatchQualityId(java.lang.Integer goodsBatchQualityId) {
		set("goods_batch_quality_id", goodsBatchQualityId);
	}
	
	public java.lang.Integer getGoodsBatchQualityId() {
		return getInt("goods_batch_quality_id");
	}
	
	public void setBatch(java.lang.String batch) {
		set("batch", batch);
	}
	
	public java.lang.String getBatch() {
		return getStr("batch");
	}
	
	public void setQuality(java.lang.String quality) {
		set("quality", quality);
	}
	
	public java.lang.String getQuality() {
		return getStr("quality");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

