package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenantAdmin<M extends BaseTenantAdmin<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setEncrypt(java.lang.String encrypt) {
		set("encrypt", encrypt);
	}
	
	public java.lang.String getEncrypt() {
		return getStr("encrypt");
	}
	
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}
	
	public void setActiveStatus(java.lang.Integer activeStatus) {
		set("active_status", activeStatus);
	}
	
	public java.lang.Integer getActiveStatus() {
		return getInt("active_status");
	}
	
	public void setLoginFlag(java.lang.Boolean loginFlag) {
		set("login_flag", loginFlag);
	}
	
	public java.lang.Boolean getLoginFlag() {
		return getBoolean("login_flag");
	}
	
	public void setMainAccountFlag(java.lang.Boolean mainAccountFlag) {
		set("main_account_flag", mainAccountFlag);
	}
	
	public java.lang.Boolean getMainAccountFlag() {
		return getBoolean("main_account_flag");
	}
	
	public void setFirstLoginIp(java.lang.String firstLoginIp) {
		set("first_login_ip", firstLoginIp);
	}
	
	public java.lang.String getFirstLoginIp() {
		return getStr("first_login_ip");
	}
	
	public void setFirstLoginTime(java.util.Date firstLoginTime) {
		set("first_login_time", firstLoginTime);
	}
	
	public java.util.Date getFirstLoginTime() {
		return getDate("first_login_time");
	}
	
	public void setLastLoginIp(java.lang.String lastLoginIp) {
		set("last_login_ip", lastLoginIp);
	}
	
	public java.lang.String getLastLoginIp() {
		return getStr("last_login_ip");
	}
	
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	public java.util.Date getLastLoginTime() {
		return getDate("last_login_time");
	}
	
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}
	
	public void setLoginError(java.lang.Integer loginError) {
		set("login_error", loginError);
	}
	
	public java.lang.Integer getLoginError() {
		return getInt("login_error");
	}
	
	public void setLoginCount(java.lang.Integer loginCount) {
		set("login_count", loginCount);
	}
	
	public java.lang.Integer getLoginCount() {
		return getInt("login_count");
	}
	
	public void setMac(java.lang.String mac) {
		set("mac", mac);
	}
	
	public java.lang.String getMac() {
		return getStr("mac");
	}
	
	public void setOnlineTimes(java.lang.Integer onlineTimes) {
		set("online_times", onlineTimes);
	}
	
	public java.lang.Integer getOnlineTimes() {
		return getInt("online_times");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

