package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsAttribute<M extends BaseGoodsAttribute<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setAttrType(java.lang.Integer attrType) {
		set("attr_type", attrType);
	}
	
	public java.lang.Integer getAttrType() {
		return getInt("attr_type");
	}
	
	public void setAttrValues(java.lang.String attrValues) {
		set("attr_values", attrValues);
	}
	
	public java.lang.String getAttrValues() {
		return getStr("attr_values");
	}
	
	public void setDefaultFlag(java.lang.Boolean defaultFlag) {
		set("default_flag", defaultFlag);
	}
	
	public java.lang.Boolean getDefaultFlag() {
		return getBoolean("default_flag");
	}
	
	public void setDataStatus(java.lang.Integer dataStatus) {
		set("data_status", dataStatus);
	}
	
	public java.lang.Integer getDataStatus() {
		return getInt("data_status");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

