package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraderIncomeExpensesFund<M extends BaseTraderIncomeExpensesFund<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setTraderIncomeExpensesId(java.lang.Integer traderIncomeExpensesId) {
		set("trader_income_expenses_id", traderIncomeExpensesId);
	}
	
	public java.lang.Integer getTraderIncomeExpensesId() {
		return getInt("trader_income_expenses_id");
	}
	
	public void setTraderBalanceAccountId(java.lang.Integer traderBalanceAccountId) {
		set("trader_balance_account_id", traderBalanceAccountId);
	}
	
	public java.lang.Integer getTraderBalanceAccountId() {
		return getInt("trader_balance_account_id");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setFundTime(java.util.Date fundTime) {
		set("fund_time", fundTime);
	}
	
	public java.util.Date getFundTime() {
		return getDate("fund_time");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

