package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInventoryStockLog<M extends BaseInventoryStockLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGoodsInfoId(java.lang.Integer goodsInfoId) {
		set("goods_info_id", goodsInfoId);
	}
	
	public java.lang.Integer getGoodsInfoId() {
		return getInt("goods_info_id");
	}
	
	public void setSpec1Id(java.lang.Integer spec1Id) {
		set("spec_1_id", spec1Id);
	}
	
	public java.lang.Integer getSpec1Id() {
		return getInt("spec_1_id");
	}
	
	public void setSpecOption1Id(java.lang.Integer specOption1Id) {
		set("spec_option_1_id", specOption1Id);
	}
	
	public java.lang.Integer getSpecOption1Id() {
		return getInt("spec_option_1_id");
	}
	
	public void setSpec2Id(java.lang.Integer spec2Id) {
		set("spec_2_id", spec2Id);
	}
	
	public java.lang.Integer getSpec2Id() {
		return getInt("spec_2_id");
	}
	
	public void setSpecOption2Id(java.lang.Integer specOption2Id) {
		set("spec_option_2_id", specOption2Id);
	}
	
	public java.lang.Integer getSpecOption2Id() {
		return getInt("spec_option_2_id");
	}
	
	public void setSpec3Id(java.lang.Integer spec3Id) {
		set("spec_3_id", spec3Id);
	}
	
	public java.lang.Integer getSpec3Id() {
		return getInt("spec_3_id");
	}
	
	public void setSpecOption3Id(java.lang.Integer specOption3Id) {
		set("spec_option_3_id", specOption3Id);
	}
	
	public java.lang.Integer getSpecOption3Id() {
		return getInt("spec_option_3_id");
	}
	
	public void setUnitId(java.lang.Integer unitId) {
		set("unit_id", unitId);
	}
	
	public java.lang.Integer getUnitId() {
		return getInt("unit_id");
	}
	
	public void setRemainNumber(java.math.BigDecimal remainNumber) {
		set("remain_number", remainNumber);
	}
	
	public java.math.BigDecimal getRemainNumber() {
		return getBigDecimal("remain_number");
	}
	
	public void setChangeNumber(java.math.BigDecimal changeNumber) {
		set("change_number", changeNumber);
	}
	
	public java.math.BigDecimal getChangeNumber() {
		return getBigDecimal("change_number");
	}
	
	public void setIoType(java.lang.Integer ioType) {
		set("io_type", ioType);
	}
	
	public java.lang.Integer getIoType() {
		return getInt("io_type");
	}
	
	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}
	
	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}
	
	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

