package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenantOperLog<M extends BaseTenantOperLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setTenantAdminId(java.lang.Integer tenantAdminId) {
		set("tenant_admin_id", tenantAdminId);
	}
	
	public java.lang.Integer getTenantAdminId() {
		return getInt("tenant_admin_id");
	}
	
	public void setOperPerson(java.lang.String operPerson) {
		set("oper_person", operPerson);
	}
	
	public java.lang.String getOperPerson() {
		return getStr("oper_person");
	}
	
	public void setOperTime(java.util.Date operTime) {
		set("oper_time", operTime);
	}
	
	public java.util.Date getOperTime() {
		return getDate("oper_time");
	}
	
	public void setOperIp(java.lang.String operIp) {
		set("oper_ip", operIp);
	}
	
	public java.lang.String getOperIp() {
		return getStr("oper_ip");
	}
	
	public void setOperDesc(java.lang.String operDesc) {
		set("oper_desc", operDesc);
	}
	
	public java.lang.String getOperDesc() {
		return getStr("oper_desc");
	}
	
	public void setLogType(java.lang.Integer logType) {
		set("log_type", logType);
	}
	
	public java.lang.Integer getLogType() {
		return getInt("log_type");
	}
	
	public void setPlatformType(java.lang.Integer platformType) {
		set("platform_type", platformType);
	}
	
	public java.lang.Integer getPlatformType() {
		return getInt("platform_type");
	}
	
}

