package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenantOrg<M extends BaseTenantOrg<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setLogo(java.lang.String logo) {
		set("logo", logo);
	}
	
	public java.lang.String getLogo() {
		return getStr("logo");
	}
	
	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}
	
	public java.lang.String getDomain() {
		return getStr("domain");
	}
	
	public void setMode(java.lang.Integer mode) {
		set("mode", mode);
	}
	
	public java.lang.Integer getMode() {
		return getInt("mode");
	}
	
	public void setFullName(java.lang.String fullName) {
		set("full_name", fullName);
	}
	
	public java.lang.String getFullName() {
		return getStr("full_name");
	}
	
	public void setCorporate(java.lang.String corporate) {
		set("corporate", corporate);
	}
	
	public java.lang.String getCorporate() {
		return getStr("corporate");
	}
	
	public void setLicense(java.lang.String license) {
		set("license", license);
	}
	
	public java.lang.String getLicense() {
		return getStr("license");
	}
	
	public void setIndustry(java.lang.Integer industry) {
		set("industry", industry);
	}
	
	public java.lang.Integer getIndustry() {
		return getInt("industry");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setPosterUrl(java.lang.String posterUrl) {
		set("poster_url", posterUrl);
	}
	
	public java.lang.String getPosterUrl() {
		return getStr("poster_url");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

