package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerInfo<M extends BaseCustomerInfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setTraderBookAccountId(java.lang.Integer traderBookAccountId) {
		set("trader_book_account_id", traderBookAccountId);
	}
	
	public java.lang.Integer getTraderBookAccountId() {
		return getInt("trader_book_account_id");
	}
	
	public void setCustomerCategoryId(java.lang.Integer customerCategoryId) {
		set("customer_category_id", customerCategoryId);
	}
	
	public java.lang.Integer getCustomerCategoryId() {
		return getInt("customer_category_id");
	}
	
	public void setSupplierInfoId(java.lang.Integer supplierInfoId) {
		set("supplier_info_id", supplierInfoId);
	}
	
	public java.lang.Integer getSupplierInfoId() {
		return getInt("supplier_info_id");
	}
	
	public void setCustomerPriceLevelId(java.lang.Integer customerPriceLevelId) {
		set("customer_price_level_id", customerPriceLevelId);
	}
	
	public java.lang.Integer getCustomerPriceLevelId() {
		return getInt("customer_price_level_id");
	}
	
	public void setDefaultFlag(java.lang.Boolean defaultFlag) {
		set("default_flag", defaultFlag);
	}
	
	public java.lang.Boolean getDefaultFlag() {
		return getBoolean("default_flag");
	}
	
	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return getBigDecimal("discount");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setMakeManId(java.lang.Integer makeManId) {
		set("make_man_id", makeManId);
	}
	
	public java.lang.Integer getMakeManId() {
		return getInt("make_man_id");
	}
	
	public void setLastManId(java.lang.Integer lastManId) {
		set("last_man_id", lastManId);
	}
	
	public java.lang.Integer getLastManId() {
		return getInt("last_man_id");
	}
	
	public void setHandlerId(java.lang.Integer handlerId) {
		set("handler_id", handlerId);
	}
	
	public java.lang.Integer getHandlerId() {
		return getInt("handler_id");
	}
	
	public void setSourceChannel(java.lang.String sourceChannel) {
		set("source_channel", sourceChannel);
	}
	
	public java.lang.String getSourceChannel() {
		return getStr("source_channel");
	}
	
	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setMoble1(java.lang.String moble1) {
		set("moble_1", moble1);
	}
	
	public java.lang.String getMoble1() {
		return getStr("moble_1");
	}
	
	public void setMobile2(java.lang.String mobile2) {
		set("mobile_2", mobile2);
	}
	
	public java.lang.String getMobile2() {
		return getStr("mobile_2");
	}
	
	public void setFirstOrderTime(java.util.Date firstOrderTime) {
		set("first_order_time", firstOrderTime);
	}
	
	public java.util.Date getFirstOrderTime() {
		return getDate("first_order_time");
	}
	
	public void setLastOrderTime(java.util.Date lastOrderTime) {
		set("last_order_time", lastOrderTime);
	}
	
	public java.util.Date getLastOrderTime() {
		return getDate("last_order_time");
	}
	
	public void setProvinceCode(java.lang.String provinceCode) {
		set("province_code", provinceCode);
	}
	
	public java.lang.String getProvinceCode() {
		return getStr("province_code");
	}
	
	public void setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
	}
	
	public java.lang.String getProvinceName() {
		return getStr("province_name");
	}
	
	public void setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
	}
	
	public java.lang.String getCityCode() {
		return getStr("city_code");
	}
	
	public void setCityName(java.lang.String cityName) {
		set("city_name", cityName);
	}
	
	public java.lang.String getCityName() {
		return getStr("city_name");
	}
	
	public void setCountyCode(java.lang.String countyCode) {
		set("county_code", countyCode);
	}
	
	public java.lang.String getCountyCode() {
		return getStr("county_code");
	}
	
	public void setCountyName(java.lang.String countyName) {
		set("county_name", countyName);
	}
	
	public java.lang.String getCountyName() {
		return getStr("county_name");
	}
	
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}
	
	public void setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
	}
	
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}
	
	public void setPayDay(java.lang.Integer payDay) {
		set("pay_day", payDay);
	}
	
	public java.lang.Integer getPayDay() {
		return getInt("pay_day");
	}
	
	public void setDataStatus(java.lang.Integer dataStatus) {
		set("data_status", dataStatus);
	}
	
	public java.lang.Integer getDataStatus() {
		return getInt("data_status");
	}
	
	public void setBlackFlag(java.lang.Boolean blackFlag) {
		set("black_flag", blackFlag);
	}
	
	public java.lang.Boolean getBlackFlag() {
		return getBoolean("black_flag");
	}
	
	public void setCreditLimit(java.math.BigDecimal creditLimit) {
		set("credit_limit", creditLimit);
	}
	
	public java.math.BigDecimal getCreditLimit() {
		return getBigDecimal("credit_limit");
	}
	
	public void setLogisticsCompanyId(java.lang.Integer logisticsCompanyId) {
		set("logistics_company_id", logisticsCompanyId);
	}
	
	public java.lang.Integer getLogisticsCompanyId() {
		return getInt("logistics_company_id");
	}
	
	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	public java.util.Date getBirthday() {
		return getDate("birthday");
	}
	
	public void setWechat(java.lang.String wechat) {
		set("wechat", wechat);
	}
	
	public java.lang.String getWechat() {
		return getStr("wechat");
	}
	
	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}
	
	public java.lang.String getBankName() {
		return getStr("bank_name");
	}
	
	public void setBankNo(java.lang.String bankNo) {
		set("bank_no", bankNo);
	}
	
	public java.lang.String getBankNo() {
		return getStr("bank_no");
	}
	
	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}
	
	public java.lang.String getQq() {
		return getStr("qq");
	}
	
	public void setWeixinFlag(java.lang.Boolean weixinFlag) {
		set("weixin_flag", weixinFlag);
	}
	
	public java.lang.Boolean getWeixinFlag() {
		return getBoolean("weixin_flag");
	}
	
	public void setMallAuthFlag(java.lang.Boolean mallAuthFlag) {
		set("mall_auth_flag", mallAuthFlag);
	}
	
	public java.lang.Boolean getMallAuthFlag() {
		return getBoolean("mall_auth_flag");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

