package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsInfo<M extends BaseGoodsInfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGoodsCategoryId(java.lang.Integer goodsCategoryId) {
		set("goods_category_id", goodsCategoryId);
	}
	
	public java.lang.Integer getGoodsCategoryId() {
		return getInt("goods_category_id");
	}
	
	public void setGoodsType(java.lang.Integer goodsType) {
		set("goods_type", goodsType);
	}
	
	public java.lang.Integer getGoodsType() {
		return getInt("goods_type");
	}
	
	public void setSaleFlag(java.lang.Boolean saleFlag) {
		set("sale_flag", saleFlag);
	}
	
	public java.lang.Boolean getSaleFlag() {
		return getBoolean("sale_flag");
	}
	
	public void setPurchaseFlag(java.lang.Boolean purchaseFlag) {
		set("purchase_flag", purchaseFlag);
	}
	
	public java.lang.Boolean getPurchaseFlag() {
		return getBoolean("purchase_flag");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	public void setBarCode(java.lang.String barCode) {
		set("bar_code", barCode);
	}
	
	public java.lang.String getBarCode() {
		return getStr("bar_code");
	}
	
	public void setSalesVolume(java.math.BigDecimal salesVolume) {
		set("sales_volume", salesVolume);
	}
	
	public java.math.BigDecimal getSalesVolume() {
		return getBigDecimal("sales_volume");
	}
	
	public void setMainUnitId(java.lang.Integer mainUnitId) {
		set("main_unit_id", mainUnitId);
	}
	
	public java.lang.Integer getMainUnitId() {
		return getInt("main_unit_id");
	}
	
	public void setSpecFlag(java.lang.Boolean specFlag) {
		set("spec_flag", specFlag);
	}
	
	public java.lang.Boolean getSpecFlag() {
		return getBoolean("spec_flag");
	}
	
	public void setSpecName(java.lang.String specName) {
		set("spec_name", specName);
	}
	
	public java.lang.String getSpecName() {
		return getStr("spec_name");
	}
	
	public void setSupplierInfoId(java.lang.Integer supplierInfoId) {
		set("supplier_info_id", supplierInfoId);
	}
	
	public java.lang.Integer getSupplierInfoId() {
		return getInt("supplier_info_id");
	}
	
	public void setStockWarnFlag(java.lang.Boolean stockWarnFlag) {
		set("stock_warn_flag", stockWarnFlag);
	}
	
	public java.lang.Boolean getStockWarnFlag() {
		return getBoolean("stock_warn_flag");
	}
	
	public void setStockWarnType(java.lang.Integer stockWarnType) {
		set("stock_warn_type", stockWarnType);
	}
	
	public java.lang.Integer getStockWarnType() {
		return getInt("stock_warn_type");
	}
	
	public void setOrderNumber(java.math.BigDecimal orderNumber) {
		set("order_number", orderNumber);
	}
	
	public java.math.BigDecimal getOrderNumber() {
		return getBigDecimal("order_number");
	}
	
	public void setDiscountFlag(java.lang.Boolean discountFlag) {
		set("discount_flag", discountFlag);
	}
	
	public java.lang.Boolean getDiscountFlag() {
		return getBoolean("discount_flag");
	}
	
	public void setOutSenseFlag(java.lang.Boolean outSenseFlag) {
		set("out_sense_flag", outSenseFlag);
	}
	
	public java.lang.Boolean getOutSenseFlag() {
		return getBoolean("out_sense_flag");
	}
	
	public void setModifyPriceFlag(java.lang.Boolean modifyPriceFlag) {
		set("modify_price_flag", modifyPriceFlag);
	}
	
	public java.lang.Boolean getModifyPriceFlag() {
		return getBoolean("modify_price_flag");
	}
	
	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	public java.math.BigDecimal getWeight() {
		return getBigDecimal("weight");
	}
	
	public void setDataStatus(java.lang.Integer dataStatus) {
		set("data_status", dataStatus);
	}
	
	public java.lang.Integer getDataStatus() {
		return getInt("data_status");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

