package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenantExportLog<M extends BaseTenantExportLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setHandlerId(java.lang.Integer handlerId) {
		set("handler_id", handlerId);
	}
	
	public java.lang.Integer getHandlerId() {
		return getInt("handler_id");
	}
	
	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}
	
	public void setFilePath(java.lang.String filePath) {
		set("file_path", filePath);
	}
	
	public java.lang.String getFilePath() {
		return getStr("file_path");
	}
	
	public void setExportStatus(java.lang.Integer exportStatus) {
		set("export_status", exportStatus);
	}
	
	public java.lang.Integer getExportStatus() {
		return getInt("export_status");
	}
	
	public void setErrorDesc(java.lang.String errorDesc) {
		set("error_desc", errorDesc);
	}
	
	public java.lang.String getErrorDesc() {
		return getStr("error_desc");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

