package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoodsImageRef<M extends BaseGoodsImageRef<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGoodsInfoId(java.lang.Integer goodsInfoId) {
		set("goods_info_id", goodsInfoId);
	}
	
	public java.lang.Integer getGoodsInfoId() {
		return getInt("goods_info_id");
	}
	
	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}
	
	public java.lang.String getThumb() {
		return getStr("thumb");
	}
	
	public void setOriginal(java.lang.String original) {
		set("original", original);
	}
	
	public java.lang.String getOriginal() {
		return getStr("original");
	}
	
	public void setMainFlag(java.lang.Boolean mainFlag) {
		set("main_flag", mainFlag);
	}
	
	public java.lang.Boolean getMainFlag() {
		return getBoolean("main_flag");
	}
	
	public void setPosition(java.lang.Integer position) {
		set("position", position);
	}
	
	public java.lang.Integer getPosition() {
		return getInt("position");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
}

