package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraderTransferOrder<M extends BaseTraderTransferOrder<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOutAccountId(java.lang.Integer outAccountId) {
		set("out_account_id", outAccountId);
	}
	
	public java.lang.Integer getOutAccountId() {
		return getInt("out_account_id");
	}
	
	public void setOutTime(java.util.Date outTime) {
		set("out_time", outTime);
	}
	
	public java.util.Date getOutTime() {
		return getDate("out_time");
	}
	
	public void setInAccountId(java.lang.Integer inAccountId) {
		set("in_account_id", inAccountId);
	}
	
	public java.lang.Integer getInAccountId() {
		return getInt("in_account_id");
	}
	
	public void setInTime(java.util.Date inTime) {
		set("in_time", inTime);
	}
	
	public java.util.Date getInTime() {
		return getDate("in_time");
	}
	
	public void setMakeManId(java.lang.Integer makeManId) {
		set("make_man_id", makeManId);
	}
	
	public java.lang.Integer getMakeManId() {
		return getInt("make_man_id");
	}
	
	public void setLastManId(java.lang.Integer lastManId) {
		set("last_man_id", lastManId);
	}
	
	public java.lang.Integer getLastManId() {
		return getInt("last_man_id");
	}
	
	public void setHandlerId(java.lang.Integer handlerId) {
		set("handler_id", handlerId);
	}
	
	public java.lang.Integer getHandlerId() {
		return getInt("handler_id");
	}
	
	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setFee(java.math.BigDecimal fee) {
		set("fee", fee);
	}
	
	public java.math.BigDecimal getFee() {
		return getBigDecimal("fee");
	}
	
	public void setFeePayAccount(java.lang.Integer feePayAccount) {
		set("fee_pay_account", feePayAccount);
	}
	
	public java.lang.Integer getFeePayAccount() {
		return getInt("fee_pay_account");
	}
	
	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}
	
	public void setAuditStatus(java.lang.Integer auditStatus) {
		set("audit_status", auditStatus);
	}
	
	public java.lang.Integer getAuditStatus() {
		return getInt("audit_status");
	}
	
	public void setAuditorId(java.lang.Integer auditorId) {
		set("auditor_id", auditorId);
	}
	
	public java.lang.Integer getAuditorId() {
		return getInt("auditor_id");
	}
	
	public void setAuditTime(java.util.Date auditTime) {
		set("audit_time", auditTime);
	}
	
	public java.util.Date getAuditTime() {
		return getDate("audit_time");
	}
	
	public void setAuditDesc(java.lang.String auditDesc) {
		set("audit_desc", auditDesc);
	}
	
	public java.lang.String getAuditDesc() {
		return getStr("audit_desc");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

