package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTraderFundOrder<M extends BaseTraderFundOrder<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setTraderBalanceAccountId(java.lang.Integer traderBalanceAccountId) {
		set("trader_balance_account_id", traderBalanceAccountId);
	}
	
	public java.lang.Integer getTraderBalanceAccountId() {
		return getInt("trader_balance_account_id");
	}
	
	public void setRefOrderType(java.lang.Integer refOrderType) {
		set("ref_order_type", refOrderType);
	}
	
	public java.lang.Integer getRefOrderType() {
		return getInt("ref_order_type");
	}
	
	public void setRefOrderId(java.lang.Integer refOrderId) {
		set("ref_order_id", refOrderId);
	}
	
	public java.lang.Integer getRefOrderId() {
		return getInt("ref_order_id");
	}
	
	public void setRefOrderCode(java.lang.String refOrderCode) {
		set("ref_order_code", refOrderCode);
	}
	
	public java.lang.String getRefOrderCode() {
		return getStr("ref_order_code");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setFundFlow(java.lang.Integer fundFlow) {
		set("fund_flow", fundFlow);
	}
	
	public java.lang.Integer getFundFlow() {
		return getInt("fund_flow");
	}
	
	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}
	
	public java.util.Date getOrderTime() {
		return getDate("order_time");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

