package com.bytechainx.psi.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTenantPayOrderLog<M extends BaseTenantPayOrderLog<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
	}
	
	public java.lang.Integer getOrderType() {
		return getInt("order_type");
	}
	
	public void setRefOrderId(java.lang.Integer refOrderId) {
		set("ref_order_id", refOrderId);
	}
	
	public java.lang.Integer getRefOrderId() {
		return getInt("ref_order_id");
	}
	
	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}
	
	public void setPayOrderId(java.lang.String payOrderId) {
		set("pay_order_id", payOrderId);
	}
	
	public java.lang.String getPayOrderId() {
		return getStr("pay_order_id");
	}
	
	public void setErrorMsg(java.lang.String errorMsg) {
		set("error_msg", errorMsg);
	}
	
	public java.lang.String getErrorMsg() {
		return getStr("error_msg");
	}
	
	public void setRealName(java.lang.String realName) {
		set("real_name", realName);
	}
	
	public java.lang.String getRealName() {
		return getStr("real_name");
	}
	
	public void setOrderName(java.lang.String orderName) {
		set("order_name", orderName);
	}
	
	public java.lang.String getOrderName() {
		return getStr("order_name");
	}
	
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	public java.math.BigDecimal getAmount() {
		return getBigDecimal("amount");
	}
	
	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}
	
	public java.util.Date getOrderTime() {
		return getDate("order_time");
	}
	
	public void setThirdpayCode(java.lang.String thirdpayCode) {
		set("thirdpay_code", thirdpayCode);
	}
	
	public java.lang.String getThirdpayCode() {
		return getStr("thirdpay_code");
	}
	
	public void setThirdpayName(java.lang.String thirdpayName) {
		set("thirdpay_name", thirdpayName);
	}
	
	public java.lang.String getThirdpayName() {
		return getStr("thirdpay_name");
	}
	
	public void setPayStatus(java.lang.Integer payStatus) {
		set("pay_status", payStatus);
	}
	
	public java.lang.Integer getPayStatus() {
		return getInt("pay_status");
	}
	
	public void setOrderDesc(java.lang.String orderDesc) {
		set("order_desc", orderDesc);
	}
	
	public java.lang.String getOrderDesc() {
		return getStr("order_desc");
	}
	
	public void setAttach(java.lang.String attach) {
		set("attach", attach);
	}
	
	public java.lang.String getAttach() {
		return getStr("attach");
	}
	
	public void setPrepayId(java.lang.String prepayId) {
		set("prepay_id", prepayId);
	}
	
	public java.lang.String getPrepayId() {
		return getStr("prepay_id");
	}
	
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

